### ISSUE TITLE
Deprecate Session as a Request attribute in favor of dedicated Helper

### ISSUE THREAD

**Issue by Slamdunk** [mezzio/mezzio-session#6]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

Hi, currently the Session instance is set as an attribute of the Request:

https://github.com/mezzio/mezzio-session/blob/eb0d8745017c12300f81c786fc9583e4b6a5bb96/src/SessionMiddleware.php#L35

In my humble opinion this is an anti-pattern:

1. Session has nothing to do with the pure concept of a Request; it leverages the Cookie functionalities, but it's not stritcly coupled to the Request itself
1. As an attribute, is basically injected everywhere, even to following Middlewares and Handlers that don't need it and shouldn't be aware of it
1. It breaks typing (and that's a smell by itself): every Request attributes derives from a HTTP Request so theoretically only scalar types are allowed; Session instead needs a non-scalar type but cannot be enforced by the PSR-7 specifications

What I propose here is the same approach used by Mezzio Helpers like [ServerUrlMiddleware](https://github.com/mezzio/mezzio-helpers/blob/master/src/ServerUrlMiddleware.php): a dedicated SessionHelper is filled and the Request untouched; if a class needs the Session, its factory must inject the SessionHelper to it, otherwise the Session is unreachable.

The same issue affects other components (see [AuthenticationMiddleware.php](https://github.com/mezzio/mezzio-authentication/blob/11fc15d78fe515db3a25ade2fabcbf79cf38493e/src/AuthenticationMiddleware.php#L37)) but Session seems to me the first one to start topic with.

Ping @Ocramius for https://twitter.com/Ocramius/status/1244964513578876928

**Comment by Ocramius** [comment]
I disagree here, since a session is inherently part of a request: whether that session is associated with data not contained in the request or associated with it (via identifier) and saved server-side is a detail.

I agree that a mutable session payload should indeed be removed, moving to an immutable session concept instead.

**Comment by Ocramius** [comment]
(note: had this discussion multiple times while discussing https://github.com/psr7-sessions/storageless)

**Comment by Ocramius** [comment]
To be clear, the following holds true for JWT sessions:

```hs
session :: Request -> Maybe SessionData
```

While server-side persistent sessions are a bit more tricky (notice the added `IO`):

```
sessionId :: Request -> Maybe SessionId
session :: SessionId -> IO (Maybe SessionData)
```

This assumes immutable `Request`, ` SessionId` and `SessionData`

**Comment by Slamdunk** [comment]
> I disagree here, since a session is inherently part of a request: whether that session is associated with data not contained in the request or associated with it (via identifier) and saved server-side is a detail.

> (note: had this discussion multiple times while discussing https://github.com/psr7-sessions/storageless)

I'm reading the topics: I get the point and I'm going to close the issue here, nevertheless it still seems dirty to me. It's so easy to sneak `$request->getAttribute('session')['foo'] = 'hugedata';` into the code without noticing it during a PR review; especially on storageless, session manipulation shall be clear and easy to maintain, the exact opposite of request attributes :disappointed: 

Thanks for the care in the reply

**Comment by Ocramius** [comment]
> I'm reading the topics: I get the point and I'm going to close the issue here, nevertheless it still seems dirty to me. It's so easy to sneak `$request->getAttribute('session')['foo'] = 'hugedata';` into the code without noticing it during a PR review; especially on storageless, session manipulation shall be clear and easy to maintain, the exact opposite of request attributes 😞

I think I have tests for that in the other library, but it is indeed true that we could improve the design of a session value type, making it immutable and strict.
